language: node_js
os:
  - linux
  - osx
env:
  - SKIP_DTRACE=1
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
  - '6'
  - node
sudo: false
script:
  - 'npm test'
notifications:
  webhooks:
    urls:
      - 'https://www.travisbuddy.com/'
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
